---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tribo-devops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tribo-devops
  source:
    repoURL: https:/github.com/vitor-caetano/poc-argocd.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: tribo-devops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
